name: "Car Assembly Line"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create build folder
        run: mkdir build

      - name: Change directory to build
        run: cd build

      - name: Create car parts file
        run: echo "Кузов\nДвигун\nКолеса\nСидіння\nКермо" > car_parts.txt

      - name: Save build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build-artifacts

      - name: Change directory to build
        run: cd build

      - name: Test for car parts
        run: |
          grep -q "Кузов" car_parts.txt
          grep -q "Двигун" car_parts.txt
          grep -q "Колеса" car_parts.txt
          grep -q "Сидіння" car_parts.txt
          grep -q "Кермо" car_parts.txt
