name: Car Assembly Line

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up the repository
      uses: actions/checkout@v2

    - name: Create build directory
      run: mkdir build

    - name: Create text file and add details
      run: |
        cd build
        touch car.txt
        echo "Adding body..." > car.txt
        echo "Adding engine..." >> car.txt
        echo "Adding wheels..." >> car.txt

    - name: Set artifact path
      run: echo '::set-output name=artifacts::build'

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: car-artifact
        path: ${{ steps.set-path.outputs.artifacts }}

  test:
    runs-on: ubuntu-latest

    needs: build

    steps:
    - name: Set up the repository
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: car-artifact

    - name: Test the build
      run: |
        cd build
        grep "Adding body..." car.txt
        grep "Adding engine..." car.txt
        grep "Adding wheels..." car.txt
