name: 'Складання автомобіля'

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Створити папку build'
        run: mkdir build

      - name: 'Перейти в папку build'
        working-directory: ./build
        run: cd ./build

      - name: 'Створити текстовий файл'
        run: touch car.txt

      - name: 'Записати дані про деталі в файл'
        run: |
          echo "Кузов" >> car.txt
          echo "Двигун" >> car.txt
          echo "Колеса" >> car.txt
          echo "Шини" >> car.txt
          echo "Сидіння" >> car.txt

      - name: 'Визначити шлях до артефактів'
        run: echo "Шлях до артефактів:"

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: 'Перейти в папку build'
        working-directory: ./build
        run: cd ./build

      - name: 'Перевірити наявність деталей'
        run: |
          grep -q "Кузов" car.txt
          grep -q "Двигун" car.txt
          grep -q "Колеса" car.txt
          grep -q "Шини" car.txt
          grep -q "Сидіння" car.txt
